/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Algorithrm.Hashing;
import Algorithrm.ToolFile;
import demo.InfoClient;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.List;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.DatagramSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import static javax.swing.Action.MNEMONIC_KEY;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author phamc
 */
public class ChatFrame extends javax.swing.JFrame {
    StartFrame start;
    public InfoClient infomall;
    public String Name;
    private  setting methodEncrypt;
    
    
    public void setStartFrame(StartFrame st){
        start=st;
    }
    /**
     * Creates new form ChatFrame
     */
    public ChatFrame() {
        try{
            for(UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (Exception ex) {
            ex.getMessage();
        }
        
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cover = new javax.swing.JPanel();
        leftSite = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listUserOnline = new javax.swing.JScrollPane();
        listUser = new javax.swing.JPanel();
        user1 = new javax.swing.JPanel();
        avata = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        newMsg = new javax.swing.JLabel();
        user2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        user3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        user4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        user5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        user6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        chatBox = new javax.swing.JPanel();
        nameAndSetting = new javax.swing.JPanel();
        userChatWithMe = new javax.swing.JLabel();
        settingBtn = new javax.swing.JButton();
        chatArea = new javax.swing.JPanel();
        acction = new javax.swing.JPanel();
        sendBtn = new javax.swing.JButton();
        fileBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatEnter = new javax.swing.JTextArea();
        over = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Messenger");
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(204, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        cover.setBackground(new java.awt.Color(255, 255, 255));

        leftSite.setBackground(new java.awt.Color(255, 255, 255));
        leftSite.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        leftSite.setForeground(new java.awt.Color(204, 204, 204));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_resize.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 244, 250));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat Messenger");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        listUserOnline.setBackground(new java.awt.Color(255, 255, 255));
        listUserOnline.setBorder(null);
        listUserOnline.setForeground(new java.awt.Color(255, 255, 255));
        listUserOnline.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        listUserOnline.setToolTipText("");
        listUserOnline.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listUserOnline.setHorizontalScrollBar(null);

        listUser.setBackground(new java.awt.Color(255, 255, 255));

        user1.setBackground(new java.awt.Color(255, 255, 255));
        user1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        avata.setBackground(new java.awt.Color(255, 255, 255));
        avata.setForeground(new java.awt.Color(255, 255, 255));
        avata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setText("Luong");

        newMsg.setText("some message ......");

        javax.swing.GroupLayout user1Layout = new javax.swing.GroupLayout(user1);
        user1.setLayout(user1Layout);
        user1Layout.setHorizontalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addComponent(avata, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user1Layout.createSequentialGroup()
                        .addComponent(newMsg)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user1Layout.setVerticalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user1Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newMsg)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        user2.setBackground(new java.awt.Color(255, 255, 255));
        user2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Luong");

        jLabel10.setText("some message ......");

        javax.swing.GroupLayout user2Layout = new javax.swing.GroupLayout(user2);
        user2.setLayout(user2Layout);
        user2Layout.setHorizontalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user2Layout.setVerticalGroup(
            user2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        user3.setBackground(new java.awt.Color(255, 255, 255));
        user3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Luong");

        jLabel13.setText("some message ......");

        javax.swing.GroupLayout user3Layout = new javax.swing.GroupLayout(user3);
        user3.setLayout(user3Layout);
        user3Layout.setHorizontalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user3Layout.setVerticalGroup(
            user3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user3Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        user4.setBackground(new java.awt.Color(255, 255, 255));
        user4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Luong");

        jLabel16.setText("some message ......");

        javax.swing.GroupLayout user4Layout = new javax.swing.GroupLayout(user4);
        user4.setLayout(user4Layout);
        user4Layout.setHorizontalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user4Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user4Layout.setVerticalGroup(
            user4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user4Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        user5.setBackground(new java.awt.Color(255, 255, 255));
        user5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Luong");

        jLabel19.setText("some message ......");

        javax.swing.GroupLayout user5Layout = new javax.swing.GroupLayout(user5);
        user5.setLayout(user5Layout);
        user5Layout.setHorizontalGroup(
            user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user5Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user5Layout.setVerticalGroup(
            user5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user5Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        user6.setBackground(new java.awt.Color(255, 255, 255));
        user6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Luong");

        javax.swing.GroupLayout user6Layout = new javax.swing.GroupLayout(user6);
        user6.setLayout(user6Layout);
        user6Layout.setHorizontalGroup(
            user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user6Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 172, Short.MAX_VALUE))))
        );
        user6Layout.setVerticalGroup(
            user6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addGroup(user6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(user6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout listUserLayout = new javax.swing.GroupLayout(listUser);
        listUser.setLayout(listUserLayout);
        listUserLayout.setHorizontalGroup(
            listUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        listUserLayout.setVerticalGroup(
            listUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listUserLayout.createSequentialGroup()
                .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(user5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(user4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(user6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        listUserOnline.setViewportView(listUser);

        javax.swing.GroupLayout leftSiteLayout = new javax.swing.GroupLayout(leftSite);
        leftSite.setLayout(leftSiteLayout);
        leftSiteLayout.setHorizontalGroup(
            leftSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftSiteLayout.createSequentialGroup()
                .addComponent(listUserOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftSiteLayout.setVerticalGroup(
            leftSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSiteLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listUserOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        chatBox.setToolTipText("");

        nameAndSetting.setBackground(new java.awt.Color(255, 255, 255));
        nameAndSetting.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        userChatWithMe.setBackground(new java.awt.Color(255, 255, 255));
        userChatWithMe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userChatWithMe.setForeground(new java.awt.Color(78, 230, 207));
        userChatWithMe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userChatWithMe.setText("Luong");

        settingBtn.setBackground(new java.awt.Color(255, 255, 255));
        settingBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        settingBtn.setBorder(null);
        settingBtn.setContentAreaFilled(false);
        settingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameAndSettingLayout = new javax.swing.GroupLayout(nameAndSetting);
        nameAndSetting.setLayout(nameAndSettingLayout);
        nameAndSettingLayout.setHorizontalGroup(
            nameAndSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameAndSettingLayout.createSequentialGroup()
                .addComponent(userChatWithMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingBtn)
                .addGap(40, 40, 40))
        );
        nameAndSettingLayout.setVerticalGroup(
            nameAndSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameAndSettingLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(nameAndSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userChatWithMe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        chatArea.setBackground(new java.awt.Color(255, 255, 255));

        acction.setBackground(new java.awt.Color(255, 255, 255));
        acction.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        sendBtn.setBackground(new java.awt.Color(255, 255, 255));
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forward.png"))); // NOI18N
        sendBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        fileBtn.setBackground(new java.awt.Color(255, 255, 255));
        fileBtn.setForeground(new java.awt.Color(255, 255, 255));
        fileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attachment.png"))); // NOI18N
        fileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnActionPerformed(evt);
            }
        });

        chatEnter.setColumns(20);
        chatEnter.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        chatEnter.setRows(1);
        chatEnter.setMaximumSize(new java.awt.Dimension(165, 2147483647));
        jScrollPane2.setViewportView(chatEnter);

        javax.swing.GroupLayout acctionLayout = new javax.swing.GroupLayout(acction);
        acction.setLayout(acctionLayout);
        acctionLayout.setHorizontalGroup(
            acctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acctionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendBtn)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        acctionLayout.setVerticalGroup(
            acctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acctionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(acctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(fileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        over.setBackground(new java.awt.Color(255, 255, 255));
        over.setBorder(null);
        over.setForeground(new java.awt.Color(255, 255, 255));
        over.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        over.setAutoscrolls(true);

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        over.setViewportView(content);

        javax.swing.GroupLayout chatAreaLayout = new javax.swing.GroupLayout(chatArea);
        chatArea.setLayout(chatAreaLayout);
        chatAreaLayout.setHorizontalGroup(
            chatAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatAreaLayout.createSequentialGroup()
                .addGroup(chatAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(over, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chatAreaLayout.setVerticalGroup(
            chatAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatAreaLayout.createSequentialGroup()
                .addComponent(over, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chatBoxLayout = new javax.swing.GroupLayout(chatBox);
        chatBox.setLayout(chatBoxLayout);
        chatBoxLayout.setHorizontalGroup(
            chatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatBoxLayout.createSequentialGroup()
                .addGroup(chatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameAndSetting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatArea, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        chatBoxLayout.setVerticalGroup(
            chatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatBoxLayout.createSequentialGroup()
                .addComponent(nameAndSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chatArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout coverLayout = new javax.swing.GroupLayout(cover);
        cover.setLayout(coverLayout);
        coverLayout.setHorizontalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverLayout.createSequentialGroup()
                .addComponent(leftSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        coverLayout.setVerticalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chatBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cover, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int turn = 0;
    private int indexUserContent = -1;
    
    public void setIndexUser(int index) {
        this.indexUserContent = index;
    }
    public int getIndexUser() {
        return indexUserContent;
    }
    
    public void setEditContentMsg(boolean bol) {
        chatEnter.setEditable(bol);
    }
    
    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        String msg = chatEnter.getText();
        if (turn == 0 && !"".equals(chatEnter.getText())) {
            try {
                addUserMsg(true, chatEnter.getText(), false);
            } catch (BadLocationException ex) {
                Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            turn = 1;
        }
        else if (turn == 1 && !"".equals(chatEnter.getText())) {
            try {
                addUserMsg(true, chatEnter.getText(), false);
            } catch (BadLocationException ex) {
                Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            turn = 0;
        }
        chatEnter.setText("");
        System.out.print(start);
        DatagramSocket socket = start.getChoose().cnn.getSocket();
        String args[] = new String[3];
        args[0]=listUserInfo.get(indexUserContent).getIP();
        args[1]=String.valueOf(listUserInfo.get(indexUserContent).getPort());
        args[2]=msg;
        try {
            start.getChoose().cnn.Backend(args);
        } catch (Exception ex) {
            Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_sendBtnActionPerformed
    private setting AlgorithmInfo;
    private Hashing vHashing = new Hashing();
    private ToolFile toolfile = new ToolFile();
    public setting getAlgorithm(){
        return AlgorithmInfo;
    }
    private void fileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File("."));
        fc.setDialogTitle("Choose a file");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File file_ecrypt;
        if (fc.showOpenDialog(fileBtn) == JFileChooser.APPROVE_OPTION && indexUserContent > - 1) {
            System.out.print("You choose: " + fc.getSelectedFile().getName());
            try {
                addUserMsg(true, fc.getSelectedFile().getName(), true);
                /*Encrypt*/
                file_ecrypt=fc.getSelectedFile();
                //toolfile.AppendByte(file_ecrypt,1024);
                //file_ecrypt=new File(file_ecrypt.getPath());
                 start.getChoose().cnn.progressFile().setHASH(vHashing.getValueHash(AlgorithmInfo.getAlgorithmInfo().getHashFunction(), file_ecrypt.getPath()));
                if (AlgorithmInfo!=null){
                    file_ecrypt=AlgorithmInfo.getAlgorithmInfo().vprogressAlgorithm.EncryptAlgorithmForFile(fc.getSelectedFile());
                }
                /*end*/
                start.getChoose().cnn.progressFile().sentfile(file_ecrypt);
                
            } catch (BadLocationException ex) {
                Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Throwable ex) {
                Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_fileBtnActionPerformed

    private void settingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingBtnActionPerformed
        // TODO add your handling code here:
        AlgorithmInfo = new setting();
        AlgorithmInfo.setVisible(true);
        
    }//GEN-LAST:event_settingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acction;
    private javax.swing.JLabel avata;
    private javax.swing.JPanel chatArea;
    private javax.swing.JPanel chatBox;
    private javax.swing.JTextArea chatEnter;
    private javax.swing.JPanel content;
    private javax.swing.JPanel cover;
    private javax.swing.JButton fileBtn;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftSite;
    private javax.swing.JPanel listUser;
    private javax.swing.JScrollPane listUserOnline;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel name;
    private javax.swing.JPanel nameAndSetting;
    private javax.swing.JLabel newMsg;
    private javax.swing.JScrollPane over;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton settingBtn;
    private javax.swing.JPanel user1;
    private javax.swing.JPanel user2;
    private javax.swing.JPanel user3;
    private javax.swing.JPanel user4;
    private javax.swing.JPanel user5;
    private javax.swing.JPanel user6;
    private javax.swing.JLabel userChatWithMe;
    // End of variables declaration//GEN-END:variables
   
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/conversation.png")));
        listUserOnline.setBorder(BorderFactory.createEmptyBorder());
        listUserOnline.getViewport().setBackground(Color.WHITE);
        
        
        content.removeAll();
        over.getVerticalScrollBar().setUnitIncrement(16);
        
        listUser.removeAll();
        listUserOnline.getVerticalScrollBar().setUnitIncrement(16);
        
        
        chatEnter.setLineWrap( true );
        chatEnter.setWrapStyleWord( true );
        chatEnter.setEditable(false);
        
        /*addUser("a");
        addUser("b");*/
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        final CloseAction closeAction = new CloseAction(this, this);
        this.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosing(WindowEvent e) {
               try {
                   closeAction.confirmClosing();
               } catch (IOException ex) {
                   Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
               }
           }
        });
             
    }

    private final ArrayList<javax.swing.JPanel> listUserUI = new ArrayList<>();
    private final ArrayList<javax.swing.JLabel> listUserNameUI = new ArrayList<>();
    private final ArrayList<javax.swing.JLabel> listUserAvataUI = new ArrayList<>();
    private final ArrayList<javax.swing.JLabel> listUserNewestMsgUI = new ArrayList<>();
    public final ArrayList<InfoClient> listUserInfo = new ArrayList<>();
    
    
    GridBagLayout layoutUser = new GridBagLayout();
    GridBagConstraints layoutUserConstraints = new GridBagConstraints();
    int layoutXUser = 0, layoutYUser = 0;
    
    public void addUser(InfoClient info){
        listUserInfo.add(info);

        listUserUI.add(new javax.swing.JPanel());
        listUserNameUI.add(new javax.swing.JLabel());
        listUserAvataUI.add(new javax.swing.JLabel());
        listUserNewestMsgUI.add(new javax.swing.JLabel());
        
        
        javax.swing.JPanel user = listUserUI.get(listUserUI.size()-1);
        javax.swing.JLabel avataUser = listUserAvataUI.get(listUserUI.size()-1);
        javax.swing.JLabel nameUser = listUserNameUI.get(listUserUI.size()-1);
        javax.swing.JLabel newestMsg = listUserNewestMsgUI.get(listUserUI.size()-1);
            
        
        user.addMouseListener(new MyMouseListener(this, listUserUI, listUserUI.size() - 1, content));
        
        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        avataUser.setBackground(new java.awt.Color(255, 255, 255));
        avataUser.setForeground(new java.awt.Color(255, 255, 255));
        avataUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avataUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N

        nameUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameUser.setText(info.getName());

        newestMsg.setText("......");

        javax.swing.GroupLayout user1Layout = new javax.swing.GroupLayout(user);
        user.setLayout(user1Layout);
        user1Layout.setHorizontalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user1Layout.createSequentialGroup()
                .addComponent(avataUser, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(user1Layout.createSequentialGroup()
                        .addComponent(newestMsg)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );
        user1Layout.setVerticalGroup(
            user1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avataUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(user1Layout.createSequentialGroup()
                .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newestMsg)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        
        layoutUserConstraints.anchor = GridBagConstraints.CENTER;

        
        listUser.setLayout(layoutUser);
        layoutUserConstraints.gridy = layoutYUser;
        listUser.add(user, layoutUserConstraints);
        
        layoutYUser++;
        
        listUser.revalidate();
        listUser.repaint();
    }
    
    private ArrayList<javax.swing.JTextPane> listMsg = new ArrayList<>();
    GridBagLayout layoutMsg = new GridBagLayout();
    GridBagConstraints layoutConstraints = new GridBagConstraints();
    int layoutX = 0, layoutY = 0;
    StyleContext context;
    StyledDocument document ;
    Style style;
    public void addUserMsg(boolean msgOfMe, String msgContent, boolean isFile) throws BadLocationException {
        
        
        
        
        String msg = preProcessString(msgContent, 50);
        context = new StyleContext();
        document = new DefaultStyledDocument(context);

        style = context.getStyle(StyleContext.DEFAULT_STYLE);
        if(isFile)
            StyleConstants.setUnderline(style, true);
        else
            StyleConstants.setUnderline(style, false);
        document.insertString(document.getLength(), msg, style);
        
        listMsg.add(new javax.swing.JTextPane(document));
        
        if(msgOfMe) {            
            listMsg.get(listMsg.size()-1).setBackground(new java.awt.Color(57, 221, 57));
            listMsg.get(listMsg.size()-1).setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N        
            listMsg.get(listMsg.size()-1).setForeground(new java.awt.Color(255, 255, 255));
            //listMsg.get(listMsg.size()-1).setText(msg);
            listMsg.get(listMsg.size()-1).setOpaque(true);
            listMsg.get(listMsg.size()-1).setEditable(false);
            layoutConstraints.insets = new Insets(10,100,10,10);
            layoutConstraints.anchor = GridBagConstraints.LINE_END;
        }
        else {
            listMsg.get(listMsg.size()-1).setBackground(new java.awt.Color(242, 242, 242));
            listMsg.get(listMsg.size()-1).setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            //listMsg.get(listMsg.size()-1).setText(msg);
            listMsg.get(listMsg.size()-1).setOpaque(true);
            layoutConstraints.insets = new Insets(10,10,10,100);
            listMsg.get(listMsg.size()-1).setEditable(false);
            layoutConstraints.anchor = GridBagConstraints.LINE_START;
            
        }
        
        //       
        content.setLayout(layoutMsg);
        layoutConstraints.gridy = layoutY;
        layoutConstraints.ipadx = 10;
        layoutConstraints.ipady = 5;
        
        content.add(listMsg.get(listMsg.size()-1), layoutConstraints);
        
        layoutY++;
        content.revalidate();
        content.repaint();
              
        
        over.getVerticalScrollBar().setValue(over.getVerticalScrollBar().getMaximum());
    }

    private String preProcessString(String msgContent, int numCharInCol) {
           ArrayList<String> splitStr = new ArrayList<String>();
           int sz = msgContent.length();
           int loop = sz/numCharInCol;
           int startIndex = 0;
           for (int i = 0; i <= loop; i++) {
               if(i == loop) {
                   splitStr.add(new String(msgContent.substring(startIndex)));
               }
               else {
                   splitStr.add(new String(msgContent.substring(startIndex, (i+1)*numCharInCol)));
                   startIndex = (i+1)*numCharInCol + 1;
               }
           }
           
           String rel = splitStr.get(0);
           for (int i = 1; i < splitStr.size(); i++) {
               rel += "\n" + splitStr.get(i);
           }
           return rel;
    }
    
    public void removeAllUser() {
        listUser.removeAll();
        listUser.revalidate();
        listUser.repaint();
        
    }

    public void setNameUserChatWithMe(String name) {
        userChatWithMe.setText(name);
        userChatWithMe.revalidate();
        userChatWithMe.repaint();
    }
    public String getNameUserChatWithMe() {
        return userChatWithMe.getText();
    }
}

class MyMouseListener implements MouseListener {
    ArrayList<javax.swing.JPanel> listUser;
    int indexUserChoosed;
    private ChatFrame frame;
    javax.swing.JPanel content;
    public MyMouseListener(ChatFrame frame ,ArrayList<javax.swing.JPanel> listUser, int indexUserChoosed, javax.swing.JPanel content) {
        this.listUser = listUser;
        this.indexUserChoosed = indexUserChoosed;
        this.frame = frame;
        this.content = content;
    }
    
    
    @Override
    public void mouseClicked(MouseEvent event) {
    } 

    @Override
    public void mousePressed(MouseEvent e) {
        if(indexUserChoosed != frame.getIndexUser()) {
            content.removeAll();
            content.revalidate();
            content.repaint();
            listUser.get(indexUserChoosed).setBackground(new java.awt.Color(245, 245, 245));
            for(int i = 0; i < listUser.size(); i++) {
                if (i != indexUserChoosed) {
                    listUser.get(i).setBackground(new java.awt.Color(255, 255, 255));
                }
            }
            frame.setIndexUser(indexUserChoosed);
            frame.setEditContentMsg(true);
            frame.setNameUserChatWithMe(frame.listUserInfo.get(indexUserChoosed).getName());
            try {
                frame.start.getChoose().cnn.setTCPforTranferFile(frame.listUserInfo.get(indexUserChoosed).getIP());
            } catch (Exception ex) {
                Logger.getLogger(MyMouseListener.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.print(frame.listUserInfo.get(indexUserChoosed).getName());
        }
        
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}



class CloseAction extends AbstractAction {
    private final JFrame mainFrame;
    private StartFrame start;
    private ChatFrame chat;
    public InfoClient infomall;
    public String Name;
    public CloseAction(JFrame mainFrame, ChatFrame chatFrame) {
       super("Exit");
       putValue(MNEMONIC_KEY, KeyEvent.VK_X);
       this.mainFrame = mainFrame;
       this.infomall=infomall;
       this.chat= chatFrame;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            confirmClosing();
        } catch (IOException ex) {
            Logger.getLogger(CloseAction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void confirmClosing() throws IOException {
        int confirmed = JOptionPane.showConfirmDialog(mainFrame,
            "Are you sure you want to quit?", "Confirm quit",
            JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            // clean up code
            System.out.print(chat.getNameUserChatWithMe());
            infomall=new InfoClient(null,0,chat.getNameUserChatWithMe());
            Socket sockets = new Socket("192.168.228.50",7777);
            ObjectOutputStream objOut = new ObjectOutputStream(sockets.getOutputStream());
            objOut.writeObject(infomall);
            System.exit(0);
        }
   }
}